services:
  main_app:
    build:
      context: ./main_app
      dockerfile: Dockerfile
    container_name: main_app
    networks:
      - app-network
    ports:
      - "5000:5000"
    env_file:
      - .env

  db_app:
    build:
      context: ./db_app 
      dockerfile: Dockerfile
    container_name: db_app
    networks:
      - app-network
    ports:
      - "5001:5001"
    env_file:
      - .env

  webcamera_app:
    build:
      context: ./webcamera_app
      dockerfile: Dockerfile
    container_name: webcamera_app
    networks:
      - app-network
    ports:
      - "5454:5454"
    env_file:
      - .env
    devices:
      - "/dev/video0:/dev/video0"

  wiki_app:
    build:
      context: ./wiki_app
      dockerfile: Dockerfile
    container_name: wiki_app
    networks:
      - app-network
    ports:
      - "8000:8000"

networks:
  app-network:
    driver: bridge

volumes:
  uploads:
