version: '3'
services:
  main_app:
    build:
      context: .  # Set context to root directory
      dockerfile: ./main_app/Dockerfile
    container_name: main_app
    networks:
      - app-network
    ports:
      - "5000:5000"

  db_app:
    build:
      context: .  # Set context to root directory
      dockerfile: ./db_app/Dockerfile
    container_name: db_app
    networks:
      - app-network
    ports:
      - "5001:5001"

  webcamera_app:
    build:
      context: .  # Set context to root directory
      dockerfile: ./webcamera_app/Dockerfile
    container_name: webcamera_app
    networks:
      - app-network
    ports:
      - "5454:5454"

  mongo:
    image: mongo
    container_name: mongo
    networks:
      - app-network
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge
